---
listen:
  port: 55757
mysql:
  db: crh
  host: mysql
  port: 3306
  user: crh
  pass: VqumC5PRCpYLtRb2FV5n
redis:
  host: redis
  port: 6379
  db: 7
  pass: pFG64SBbhGB56K8Cv5eZbrdQ
logfile: logs/crh.log