---
#第一步，先创建crh专用pv
#+里面放只放应用日志
apiVersion: v1
kind: PersistentVolume
metadata:
  name: crh-pv
  labels:
    app: crh
spec:
  capacity:
    storage: 300Mi
  accessModes:
  - ReadWriteOnce
  - ReadOnlyMany
  #persistentVolumeReclaimPolicy: Retain
  nfs:
    server: 192.168.30.218
    path: /data/pv/cpluto/crh
---
#第二步，再创建专用pvc
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: crh-all
  namespace: cpluto
spec:
  resources:
    requests:
      storage: 300Mi
  selector:
    matchLabels:
      app: crh
  accessModes:
  - ReadWriteOnce
---
#第三步，创建普通应用的部署集
apiVersion: apps/v1
kind: Deployment
metadata:
  name: crh
  namespace: cpluto
  labels:
    app: crh
spec:
  replicas: 3
  selector:
    matchLabels:
      app: crh
  template:
    metadata:
      labels:
        app: crh
    spec:
      containers:
      - name: crh
        image: harbor.ceibsonline.cn:5000/cpluto/crh:1.7.5
        env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.name
        imagePullPolicy: Always
        resources:
          requests:
            cpu: 150m
            memory: 150Mi
        livenessProbe:
          tcpSocket:
            port: 55757
        readinessProbe:
          tcpSocket:
            port: 55757
          initialDelaySeconds: 5
          periodSeconds: 10
        ports:
        - containerPort: 55757
        volumeMounts:
        - mountPath: "/app/logs"
          name: crh
          subPathExpr: $(POD_NAME)
      imagePullSecrets:
      - name: ceibsonline
      volumes:
      - name: crh
        persistentVolumeClaim:
          claimName: crh-all
---
#第四步，创建服务
apiVersion: v1
kind: Service
metadata:
  name: crh
  namespace: cpluto
spec:
  type: NodePort
  ports:
  - port: 55757
    protocol: TCP
    targetPort: 55757
    nodePort: 30057
  selector:
    app: crh
